### ISSUE TITLE
Source code highlighting

### ISSUE THREAD

**Issue by rodrigobahiense** [JustusAdam/language-asciidoc#3]
Hi there.

As of version 1.1.0, syntax highlighting for source code doesn't seems to work.

Any advice? Thanks in advance.

Edit: "source code" = content inside [source, language] blocks

**Comment by JustusAdam** [comment]
Interesting ... Apparently the new grammar file I merged wasn't as good I was lead to believe. Will revert. Thanks for the tip!

**Comment by JustusAdam** [comment]
I put the old syntax file back, see if it works now (version 1.3.0)

**Comment by rodrigobahiense** [comment]
VS code shows the following error when opening .adoc files now:

![image](https://cloud.githubusercontent.com/assets/840518/11670629/33831290-9dea-11e5-9178-93408188b8ff.png)

Developer tools shows this:

![image](https://cloud.githubusercontent.com/assets/840518/11670618/1ab17cca-9dea-11e5-80c2-675a7d7e0016.png)

**Comment by JustusAdam** [comment]
Yep.  Should have tested it. Made stupid assumptions. Should work now though. Sorry for the issues.

**Comment by rodrigobahiense** [comment]
It's working now. Thank you very much! =)

**Comment by JustusAdam** [comment]
Nice, Have fun.

**Comment by antonmoiseev** [comment]
Hi @JustusAdam. The previous grammar file is a way more mature than the one from Atom's extension. Syntax highlighting for the source code blocks is easier to add than addressing all other issues. I believe we should continue use.

**Comment by JustusAdam** [comment]
You told me that before and I believed you. But as you can see that caused issues with the inline syntax highlighting so I reverted. 

If the syntax highlighting gets added to your syntax file I can use it again.

**Comment by antonmoiseev** [comment]
Justus, software is not the matter of belief you can compare how both grammars highlight the same adoc file. I wrote the Atom's grammar file from the scratch, while the VS Code's grammar was originally taken from an ST3 extension. Atom's grammar lacks support of very common Asciidoc syntax. The regexps do not handle lots of corner cases. Most of [the issues](https://github.com/asciidoctor/atom-language-asciidoc/issues) filed to Atom's extension do not even exist in the ST3 grammar. Source code block highlighting was the only strong side of the Atom's grammar file.

**Comment by JustusAdam** [comment]
The thing is though, corner cases are by for not as common as source code highlighting. A grammar that handles the rare corners hardly anyone will encounter Is not as useful as a grammar which instead handles a very common use case correctly.

In my opinion it is more important that the inline code blocks are highlighted correctly than that a list with bold is correctly displayed.

I am not very familiar with these grammar files and I don't have the time to fix it. But you said it would be easy, so why don't you add it? I presume you'd only have to copy some code from the tmLanguage file anyway.
