### ISSUE TITLE
Unpublish this on VS Code Marketplace

### ISSUE THREAD

**Issue by danyill** [JustusAdam/language-asciidoc#9]
Recently we had some discussion on the VS Code extension maintained by João Pinto and now part of the Asciidoctor organisation on Github about publishing old or deprecated extensions like this one.

(See https://github.com/asciidoctor/asciidoctor-vscode/issues/471)

Would you be willing to unpublish this extension following the [steps here](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#unpublishing-extensions) to ensure the marketplace is clean and accessible?

**Comment by JustusAdam** [comment]
Done. Have fun

**Comment by danyill** [comment]
Great, thank you :clap:
